### ISSUE TITLE
Warning about device_state_attributes in Home Assistant

### ISSUE THREAD

**Issue by posavasos** [tsunglung/xiaomi_fan_circulator#5]
I have been using the custom component since recently and I have noticed a warning about `device_state_attributes` in the logs.

Replacing `device_state_attributes` with `extra_state_attributes` in [fan.py](https://github.com/tsunglung/xiaomi_fan_circulator/blob/master/custom_components/xiaomi_fan_circulator/fan.py#L386) (line 386) seems to be enough to avoid the warning.

The same was done in [syssi/xiaomi_fan](https://github.com/syssi/xiaomi_fan/commit/0dbc247fcdd87956d167a13f1f05cc759ec077f9) in December.

**Comment by tsunglung** [comment]
This repo was not maintained any more.
The FA1/FB1 support was moved to https://github.com/tsunglung/xiaomi_fan.
